baseURL: https://bbbort.github.io/
languageCode: en-us
title: BortBortBort

module:
  imports:
    - path: github.com/imfing/hextra

enableRobotsTXT: true
enableGitInfo: true
enableEmoji: true

defaultContentLanguage: nl
languages:
  en:
    languageName: English
    weight: 1
    title: BortBortBort
  nl:
    languageName: Nederlands
    weight: 2
    title: BortBortBort

params:
  description: Graphic design for board games. Board game development. Solo design.

  navbar:
    displayTitle: true
    displayLogo: true
    width: normal
    logo:
      path: logo/BortBortBort-logo-colour.png
      dark: logo/BortBortBort-logo-darkmode.png
      link: /
      width: 100 
      height: 100

  theme:
    # light | dark | system
    default: system
    displayToggle: true

  page:
    # full (100%), wide (90rem), normal (1280px)
    width: wide

  footer:
    enable: true
    displayCopyright: true
    displayPoweredBy: false
    width: normal

    displayUpdatedDate: true
    dateFormat: "2 January 2006"

  search:
    enable: false
    type: flexsearch

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false