main:
  - name: Home
    pageRef: /
    weight: 1
  - name: Wie ben ik?
    pageRef: /karel
    weight: 2
  - name: Portfolio
    pageRef: /portfolio
    weight: 3
  - name: Contraptions
    pageRef: /contraptions
    weight: 4
  - name: Who's the King?
    pageRef: /who-the-king
    weight: 5
  - name: Contact
    pageRef: /contact
    weight: 9
  - name: BoardGameGeek
    weight: 10
    url: "https://boardgamegeek.com/boardgamedesigner/136907/karel-titeca"
    params:
      icon: bgg
 